# Generated by Django 3.0.1 on 2020-01-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ayakkabi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numara', models.IntegerField()),
                ('Adet', models.IntegerField()),
            ],
        ),
    ]
